import os.path

from setuptools import setup, find_packages



setup(name = "sensex",
      version = "0.9311",
      packages = "",
      scripts = [],
      # data_files = ["README.rst"],
      description = "Manipulate arrays of complex data structures as easily as Numpy.",
      # long_description = get_description(),
      author = "Ratin Kumar (DumbMachine)",
      author_email = "ratin.kumar.2k@gmail.com",
      maintainer = "Ratin Kumar (DumbMachine)",
      maintainer_email = "ratin.kumar.2k@gmail.com",
      url = "https://github.com/DumbMachine/sensex",
      download_url = "https://github.com/DumbMachine/sensex/release",
      license = "BSD 3-clause",
      test_suite = "tests",
      install_requires = ["pandas","bs4","numpy"],
    #   setup_requires = ["pytest-runner"],
    #   tests_require = ["pytest"],
      classifiers = [
          "Development Status :: 1 - Planning",
          # "Development Status :: 2 - Pre-Alpha",
          # "Development Status :: 3 - Alpha",
          # "Development Status :: 4 - Beta",
          # "Development Status :: 5 - Production/Stable",
          # "Development Status :: 6 - Mature",
          "Intended Audience :: Developers",
          "Intended Audience :: Information Technology",
          "Operating System :: MacOS",
          "Operating System :: POSIX",
          "Operating System :: Unix",
          "Programming Language :: Python",
          "Programming Language :: Python :: 2.7",
          "Programming Language :: Python :: 3.4",
          "Programming Language :: Python :: 3.5",
          "Programming Language :: Python :: 3.6",
          "Programming Language :: Python :: 3.7",
          "Topic :: Software Development",
          "Topic :: Utilities",
          ],
      platforms = "Any",
      )